name = "qinlongchenjie-experiment-animation-studio"
compatibility_date = "2026-03-21"

[pages]
build_output_dir = "dist"  # 90%的前端项目用dist，如果你是Next.js改".next"，Nuxt改".output/public"
build_command = "npm run build"